console.log("====Assignment No. 2: Variable Swapping====");
console.log("1] Sweety & Cutie");
console.log("Variables before Swap");
var sweety = "Sweety";
var cutie = "Cutie";
console.log(sweety, cutie);
console.log("Variables after Swap");
sweety = "Cutie";
cutie = "Sweety";
console.log(sweety, cutie);
console.log("2] Number Swapping");
console.log("Variables before Swap");
var num1 = 100;
var num2 = 200;
var num3 = 300;
console.log(num1, num2, num3);
console.log("Variables after Swap");
num1 = num2;
num2 = num3;
var temp = 100;
num3 = temp;
console.log(num1, num2, num3);
